Rework git hooks just a little bit
- Add `props.hook_args : []` to all hooks
- Add a little error handling

diff --git a/git-hooks/post-commit b/git-hooks/post-commit
--- a/git-hooks/post-commit
+++ b/git-hooks/post-commit
@@ -1,17 +1,31 @@
 #!/usr/bin/env bash
 
+>&2 echo ">>>> $0 -- $*"
+
 readonly origin_hook="$0"
 readonly track_hook="${HOME}/.git-hooks/track"
 
-if [ -f "${track_hook}" ]; then
-  commit_msg_length="$(git log --format=%B -n1 | wc -c)"; readonly commit_msg_length
-  props="$(
-    jq -c --argjson commit_msg_length "${commit_msg_length}" '. +
-      {
-        commit_msg_length: $commit_msg_length
-      }
-    ' <<< '{}'
-  )"; readonly props
-
-  "${track_hook}" "${origin_hook}" "${props}"
+if [ ! -f "${track_hook}" ]; then
+  >&2 echo "WARNING: $0 cannot find tracking hook: ${track_hook}"
+  exit 0
 fi
+
+hook_args_json_arr="$(
+  # Based on from https://stackoverflow.com/a/26809318
+  printf '%s\n' "$@" | jq -R . | jq -sc '. | map(select(length > 0))'
+)"; readonly hook_args_json_arr
+
+standard_props="$(
+  jq -c --argjson hook_args "$hook_args_json_arr" '. + { hook_args: $hook_args } ' <<< '{}'
+)"; readonly standard_props
+
+commit_msg_length="$(git log --format=%B -n1 | wc -c)"; readonly commit_msg_length
+props="$(
+  jq -c --argjson commit_msg_length "${commit_msg_length}" '. +
+    {
+      commit_msg_length: $commit_msg_length
+    }
+  ' <<< "${standard_props}"
+)"; readonly props
+
+"${track_hook}" "${origin_hook}" "${props}"
diff --git a/git-hooks/pre-push b/git-hooks/pre-push
--- a/git-hooks/pre-push
+++ b/git-hooks/pre-push
@@ -1,8 +1,24 @@
 #!/usr/bin/env bash
 
+>&2 echo ">>>> $0 -- $*"
+
 readonly origin_hook="$0"
 readonly track_hook="${HOME}/.git-hooks/track"
 
-if [ -x "${track_hook}" ]; then
-  "${track_hook}" "${origin_hook}"
+if [ ! -f "${track_hook}" ]; then
+  >&2 echo "WARNING: $0 cannot find tracking hook: ${track_hook}"
+  exit 0
 fi
+
+hook_args_json_arr="$(
+  # Based on from https://stackoverflow.com/a/26809318
+  printf '%s\n' "$@" | jq -R . | jq -sc '. | map(select(length > 0))'
+)"; readonly hook_args_json_arr
+
+standard_props="$(
+  jq -c --argjson hook_args "$hook_args_json_arr" '. + { hook_args: $hook_args } ' <<< '{}'
+)"; readonly standard_props
+
+readonly props="${standard_props}"
+
+"${track_hook}" "${origin_hook}" "${props}"
